openapi: 3.0.0
info:
  title: Game^3 API
  version: 1.0.1
  description: Game^3 API
  contact:
    name: game3-back
    url: 'https://github.com/traPtitech/game3-back'
servers:
  - url: 'http://localhost:8080/api'
    description: ローカル環境
  - url: 'https://game3.trap.games/api'
    description: 本番環境
tags:
  - name: games
    description: ゲームAPI
  - name: events
    description: イベントAPI
  - name: auth
    description: 認証API
  - name: users
    description: ユーザーAPI
  - name: contacts
    description: コンタクトAPI
paths:
  /ping:
    get:
      summary: サーバーの生存確認
      operationId: pingServer
      responses:
        '200':
          description: Pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
  /test:
    get:
      summary: テスト用
      operationId: test
      responses:
        '200':
          description: OK

  /games:
    post:
      summary: ゲームを登録
      operationId: postGame
      tags:
        - games
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PostGameRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '400':
          description: Bad Request
        '403':
          description: Forbidden

  /games/{gameId}:
    patch:
      summary: ゲーム情報を変更
      operationId: patchGame
      tags:
        - games
      parameters:
        - $ref: '#/components/parameters/gameIdInPath'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchGameRequest'
      responses:
        '204':
          description: No Content - 変更されました
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '404':
          description: Not Found

    get:
      summary: ゲーム情報を取得
      operationId: getGame
      tags:
        - games
      parameters:
        - $ref: '#/components/parameters/gameIdInPath'
      responses:
        '200':
          description: 成功 - ゲーム情報取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
        '404':
          description: Not Found
  /games/{gameId}/icon:
    get:
      summary: ゲームのアイコン画像を取得
      operationId: getGameIcon
      tags:
        - games
      parameters:
        - $ref: '#/components/parameters/gameIdInPath'
      responses:
        '200':
          description: 成功 - ゲームのアイコン画像を取得
          content:
            image/png:
              schema:
                $ref: '#/components/schemas/ImageResponse'
        '404':
          description: Not Found
  /games/{gameId}/image:
    get:
      summary: ゲームの画像を取得
      operationId: getGameImage
      tags:
        - games
      parameters:
        - $ref: '#/components/parameters/gameIdInPath'
      responses:
        '200':
          description: 成功 - ゲームの画像を取得
          content:
            image/png:
              schema:
                $ref: '#/components/schemas/ImageResponse'
        '404':
          description: Not Found

  /events:
    post:
      summary: イベントを登録
      operationId: postEvent
      tags:
        - events
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PostEventRequest'

      responses:
        '201':
          description: 成功 - イベント登録
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Bad Request

    get:
      summary: イベントのリストを取得
      operationId: getEvents
      tags:
        - events
      responses:
        '200':
          description: 成功 - イベントリスト取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '404':
          description: Not Found
  /events/now:
    get:
      summary: 開催中のイベントを取得
      operationId: getCurrentEvent
      tags:
        - events
      responses:
        '200':
          description: 成功 - 開催中のイベント取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Not Found
  /events/{eventId}:
    patch:
      summary: イベントの情報を変更
      operationId: patchEvent
      tags:
        - events
      parameters:
        - $ref: '#/components/parameters/eventIdInPath'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchEventRequest'
      responses:
        '204':
          description: No Content - 変更されました
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '404':
          description: Not Found
    get:
      summary: イベントの情報を取得
      operationId: getEvent
      tags:
        - events
      parameters:
        - $ref: '#/components/parameters/eventIdInPath'
      responses:
        '200':
          description: 成功 - イベント情報取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Not Found
  /events/{eventId}/image:
    get:
      summary: イベントの画像を取得
      operationId: getEventImage
      tags:
        - events
      parameters:
        - $ref: '#/components/parameters/eventIdInPath'
      responses:
        '200':
          description: 成功 - イベント画像取得
          content:
            image/png:
              schema:
                $ref: '#/components/schemas/ImageResponse'
        '404':
          description: Not Found
  /events/{eventId}/games:
    get:
      summary: イベントに登録されているゲームのリストを取得
      operationId: getEventGames
      tags:
        - events
        - games
      parameters:
        - $ref: '#/components/parameters/eventIdInPath'
      responses:
        '200':
          description: 成功 - イベントに登録されているゲームのリスト取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
        '404':
          description: Not Found
  /events/{eventId}/csv:
    get:
      summary: イベントとイベントに登録されているゲームの情報をCSV形式で取得
      operationId: getEventCsv
      tags:
        - events
      parameters:
        - $ref: '#/components/parameters/eventIdInPath'
      responses:
        '200':
          description: 成功 - CSV形式で情報取得
          content:
            text/csv:
              schema:
                $ref: '#/components/schemas/GetEventCSVResponse'
        '404':
          description: Not Found

  /auth/login:
    post:
      summary: ログイン
      operationId: login
      tags:
        - auth
      description: Discord OAuthを使ったログイン。ログイン後にリダイレクトするURLを指定。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                redirect:
                  type: string
                  description: リダイレクト先のURL
      responses:
        '302':
          description: Redirect to Discord OAuth URL
          headers:
            Location:
              schema:
                type: string
                description: Discord OAuthのログインURL
            Set-Cookie:
              schema:
                type: string
                description: セッショントークン
        '400':
          description: Bad Request
  /auth/callback:
    get:
      summary: OAuth認証コールバック
      operationId: oauthCallback
      tags:
        - auth
      parameters:
        - in: query
          name: code
          required: true
          schema:
            type: string
          description: Discordからの認証コード
      responses:
        '302':
          description: Redirect to original URL
          headers:
            Location:
              schema:
                type: string
                description: もともと開いていたURL
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
  /auth/logout:
    post:
      summary: ログアウト
      operationId: logout
      tags:
        - auth
      responses:
        '204':
          description: No Content - ログアウトしました。

  /users/me:
    get:
      summary: 自分のユーザー情報を取得
      operationId: getMe
      tags:
        - users
      responses:
        '200':
          description: 成功 - ユーザー情報取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
  /users/me/games:
    get:
      summary: 自分が登録したゲームのリストを取得
      operationId: getMeGames
      tags:
        - users
      responses:
        '200':
          description: 成功 - 登録ゲームリスト取得
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items:
                      $ref: '#/components/schemas/Game'
        '404':
          description: Not Found
  /users/{userId}:
    get:
      summary: ユーザー情報を取得
      operationId: getUser
      tags:
        - users
      parameters:
        - $ref: '#/components/parameters/userIdInPath'
      responses:
        '200':
          description: 成功 - ユーザー情報取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
  /users/{userId}/games:
    get:
      summary: ユーザーが登録したゲームのリストを取得
      operationId: getUserGames
      tags:
        - users
      parameters:
        - $ref: '#/components/parameters/userIdInPath'
      responses:
        '200':
          description: 成功 - 登録ゲームリスト取得
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items:
                      $ref: '#/components/schemas/Game'
        '404':
          description: Not Found

  /contacts:
    post:
      summary: コンタクト用メールを送信
      operationId: postContacts
      tags:
        - contacts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostContactsRequest'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request

components:
  parameters:
    gameIdInPath:
      in: path
      name: gameId
      required: true
      schema:
        type: string
        description: ゲームID
    eventIdInPath:
      in: path
      name: eventId
      required: true
      schema:
        type: string
        description: イベントID
    userIdInPath:
      in: path
      name: userId
      required: true
      schema:
        type: string
        description: ユーザーID

  schemas:
    Game:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: ゲームID
        creatorName:
          type: string
          description: ゲーム作成者
        creatorPageUrl:
          type: string
          description: ゲーム作成者のページのURL
        gamePageUrl:
          type: string
          description: ゲームページのURL
        title:
          type: string
          description: 展示するゲームタイトル
        description:
          type: string
          description: ゲームの説明
        term:
          type: string
          description: 用語
        eventId:
          type: string
          format: uuid
          description: イベントID
        discordUserId:
          type: string
          description: DiscordのユーザーID
      required:
        - id
        - discordUserId
        - title

    PostGameRequest:
      type: object
      properties:
        creatorName:
          type: string
          description: ゲーム作成
        creatorPageUrl:
          type: string
          description: ゲーム作成者のページのURL
        gamePageUrl:
          type: string
          description: ゲームページのURL
        title:
          type: string
          description: 展示するゲームタイトル
          example: 'ゲームタイトル'
        description:
          type: string
          description: ゲームの説明
        icon:
          type: string
          format: binary
          description: ゲームのアイコン画像
        image:
          type: string
          format: binary
          description: ゲームの画像
      required:
        - title
        - creatorName
        - description
        - icon

    PatchGameRequest:
      type: object
      properties:
        creatorName:
          type: string
          description: ゲーム作成者
        creatorPageUrl:
          type: string
          description: ゲーム作成者のページのURL
        gamePageUrl:
          type: string
          description: ゲームページのURL
        title:
          type: string
          description: 展示するゲームタイトル
          example: 'ゲームタイトル'
        description:
          type: string
          description: ゲームの説明
        term:
          type: string
          description: 用語
        eventId:
          type: string
          format: uuid
          description: イベントID
        discordUserId:
          type: string
          description: DiscordのユーザーID
        icon:
          type: string
          format: binary
          description: ゲームのアイコン画像
        image:
          type: string
          format: binary
          description: ゲームの画像

    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: イベントID (slugとしても使用)
        title:
          type: string
          description: 'イベントのタイトル (例: 第18回)'
        gameSubmissionPeriodStart:
          type: string
          format: date-time
          description: ゲーム展示の募集開始期間
        gameSubmissionPeriodEnd:
          type: string
          format: date-time
          description: ゲーム展示の募集終了期間
      required:
        - id
        - title
        - gameSubmissionPeriodStart
        - gameSubmissionPeriodEnd

    PostEventRequest:
      type: object
      properties:
        slug:
          type: string
          description: 'slug (URL内で使用, unique)'
        title:
          type: string
          description: '第18回'
        gameSubmissionPeriodStart:
          type: string
          description: ゲーム展示の募集期間
          format: date-time
        gameSubmissionPeriodEnd:
          type: string
          description: ゲーム展示の募集期間
          format: date-time
        image:
          type: string
          format: binary
          description: パンフレット用画像
      required:
        - slug
        - title
        - gameSubmissionPeriodStart
        - gameSubmissionPeriodEnd

    PatchEventRequest:
      $ref: '#/components/schemas/PostEventRequest'

    GetEventCSVResponse:
      type: string

    PostContactsRequest:
      type: object
      properties:
        name:
          type: string
          description: 名前
        email:
          type: string
          description: メールアドレス
        message:
          type: string
          description: お問い合わせ内容
      required:
        - name
        - email
        - message

    ImageResponse:
      type: string
      format: binary

    User:
      type: object
      properties:
        userId:
          type: string
        username:
          type: string
        profileImageUrl:
          type: string
        role:
          type: string
          enum:
            - admin
            - user
